
lemon_rest_index:
    pattern: /
    defaults: { _controller: lemon_rest.index_controller:indexAction }
    requirements:
        _method: GET

lemon_rest_list:
    pattern: /{resource}
    defaults: { _controller: lemon_rest.resource_controller:listAction }
    requirements:
        _method: GET

lemon_rest_get:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:getAction }
    requirements:
        _method: GET

lemon_rest_post:
    pattern: /{resource}
    defaults: { _controller: lemon_rest.resource_controller:postAction }
    requirements:
        _method: POST

lemon_rest_put:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:putAction }
    requirements:
        _method: PUT

lemon_rest_patch:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:patchAction }
    requirements:
        _method: PATCH

lemon_rest_delete:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:deleteAction }
    requirements:
        _method: DELETE
