
lemon_rest_index:
    path: /
    defaults: { _controller: lemon_rest.index_controller:indexAction }
    methods: [GET]

lemon_rest_list:
    path: /{resource}
    defaults: { _controller: lemon_rest.resource_controller:listAction }
    methods: [GET]

lemon_rest_get:
    path: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:getAction }
    methods: [GET]

lemon_rest_post:
    path: /{resource}
    defaults: { _controller: lemon_rest.resource_controller:postAction }
    methods: [POST]

lemon_rest_put:
    path: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:putAction }
    methods: [PUT]

lemon_rest_patch:
    path: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:patchAction }
    methods: [PATCH]

lemon_rest_delete:
    path: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:deleteAction }
    methods: [DELETE]

lemon_rest_options:
    path: /{resource}
    defaults: { _controller: lemon_rest.resource_controller:optionsAction }
    methods: [OPTIONS]

lemon_rest_options_id:
    path: /{resource}/{id}
    defaults: { _controller: lemon_rest.resource_controller:optionsAction }
    methods: [OPTIONS]

