
lemon_rest_list:
    pattern: /{resource}
    defaults: { _controller: lemon.rest.controller:listAction }
    requirements:
        _method: GET

lemon_rest_get:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon.rest.controller:getAction }
    requirements:
        _method: GET

lemon_rest_post:
    pattern: /{resource}
    defaults: { _controller: lemon.rest.controller:postAction }
    requirements:
        _method: POST

lemon_rest_put:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon.rest.controller:putAction }
    requirements:
        _method: PUT

lemon_rest_delete:
    pattern: /{resource}/{id}
    defaults: { _controller: lemon.rest.controller:deleteAction }
    requirements:
        _method: DELETE
