language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.6
    - php: hhvm

install:
  - composer install --no-interaction --dev --prefer-source

script: ./vendor/bin/phpunit